### PR TITLE
add option to compare query versions

### PR DESCRIPTION
**Pull request by spasovski**
How to trigger:

The modal itself:

### CODE REVIEW

**Comment by alison985** [comment]
@spasovski Could you please resolve the merge conflicts in this PR (github now provides a nice "resolve conflicts" button in the PR itself) and handle the pagination issue mentioned in https://github.com/getredash/redash/pull/1569?

**Comment by spasovski** [comment]
Merge conflicts resolved, pagination was removed in the commit before that - but I squashed it so it won't show up...though maybe I should've let it write to the commit log.

**Comment by alison985** [comment]
Looks good to me. Merging.

**Comment by alison985** [comment]
@spasovski This seems to have a test failure:  https://circleci.com/gh/mozilla/redash/147 Could you take a look please?

**Comment by vcarciu** [comment]
I am not sure how to create multiple versions for the same query. Can you please help me there?

**Comment by spasovski** [comment]
Hi Victor. I would simply change the query text and save it which will register a new version. Repeat as necessary to create more versions.

**Comment by vcarciu** [comment]
@spasovski  : Thanks , but when trying to compare the versions , a blank page is displayed : https://www.screencast.com/t/Rqw5dwMw6r3

**Comment by ben-lantern** [comment]
Darn, looks like this feature was close to implementation but didn't make it. Would love it on the roadmap. Thanks!

**Pull request merged**
