### PR TITLE
Add last_active_at column to users page

### PR DESCRIPTION
**Pull request by alison985**
#155

### CODE REVIEW

**Comment by alison985** [comment]
@washort This works in the UI, but the following test passes and I'm not sure how to fix it:

======================================================================
FAIL: test_get_query (tests.handlers.test_queries.TestQueryResourceGet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tests/handlers/test_queries.py", line 17, in test_get_query
    self.assertResponseEqual(expected, rv.json)
  File "/app/tests/__init__.py", line 115, in assertResponseEqual
    self.assertResponseEqual(v, actual[k])
  File "/app/tests/__init__.py", line 118, in assertResponseEqual
    self.assertEqual(v, actual[k], "{} not equal (expected: {}, actual: {}).".format(k, v, actual[k]))
AssertionError: last_active_at not equal (expected: SELECT events.created_at AS events_created_at 
FROM events 
WHERE events.user_id = %(user_id_1)s ORDER BY events.created_at DESC 
 LIMIT %(param_1)s, actual: []).

**Comment by washort** [comment]
The error is because `last_active_at` is being set to a query object and the response handler is converting it to a list. Since you expect at most one result, I'd call `.first()` on that query and adjust the template to only expect a single value.

**Comment by alison985** [comment]
@washort Thanks. Updated.

**Comment by washort** [comment]
r+

**Pull request merged**
