### PR TITLE
Experimental direct-access Athena query runner

### PR DESCRIPTION
**Pull request by washort**

### CODE REVIEW

**Comment by fbertsch** [comment]
We probably want to keep the original query runner, no? We can have two separate Athena connectors in re:dash, just in case something doesn't work in either one.

**Comment by arikfr** [comment]
Very nice! Was it documented somewhere or you just reverse engineered what their JDBC library was doing?

**Comment by washort** [comment]
This was based on @robotblake's investigation into the JDBC wrapper's implementation, I believe. Example code here: https://github.com/robotblake/delphin

**Comment by arikfr** [comment]
Nice!

**Pull request merged**
