### PR TITLE
M21 rebase

### LINKED ISSUE #927: Athena schema browser not showing all tables
The schema browser for our Athena data source is showing most but not all of the tables that exist. Seems to be related to a timeout when requesting the schema data for insertion into redash's PostGreSQL database.

### LINKED ISSUE #934: Don't show empty 'example' column in schema drawer
We should not show the 'example' column in the schema drawer when samples aren't turned on for a given data source.

### LINKED ISSUE #939: More Info tooltip not displayed for Athena
### Steps to Reproduce
1. Open create a new query page and select Athena Data source
2. Hover one of the tables

### Expected results:
The more info tooltip is displayed

### Actual results:
No tooltip

### Notes/Issue
Verified in FF66 win7x64 Issue can be reproduced in STMO-RC 
Please view this screenshot: 
moreInfoTooltipAthena

### PR DESCRIPTION
**Pull request by jezdez**
## Applied commits

- fb382fd899d5bd066234ad8222f07940d55cc1e7
- e79b5ea1a86e1c17f92faa383c5fd4eb708d0b03
- c55edf5b76b2281ea06b3279d6ae112e0583077e
- 3ed49b39b30246afe64283bbbc0581d625d32cbc
- 34e430611b9dbdb32470b23377d5b0a76a252ac3
- f8fd8857d563da2450f5dffe4d3f5ed6f218bf21
- 1f29990bf337d8981efffcbff9e4bc1c8c9a0145
- b85a58bd61cfb3c6765e04baa4ed89a612c86f17
- 0abca85f03ac8313aca8fda949312d14f5aba94a
- c33f8f67964a1a9bc26c3adffad82eeec3c21e68
- c30f613360b580c99a5130ffd1a5a34539efa60a
- 4c70fe62a135286b6fb7ccfea7b661841f758847
- 5d90dbf2e28029b018bf436ba8228f152dbd8713
- cfbd41e168023a6c963be0a95944e242eac305b7
- adcfc975636bd621080afd570ef73d0564b502a4
- 8ee56c876b0816361ee62a30d6ecee7c6d1340cc
- 17acb59abbb54274d1a1eaa623efdfcebc3ef4d5
- f1d9fa08bece9ccaebd343d0f3047a0d5706dd6d
- 5a9fbb0c79aa5999ee1bc46bd0ac7f396d4d8fb4
- 62ab494cbb0545b308121d78e191315df36f6245
- 15389473769dd31b84e20a994334b08ccdaaa014
- be8b4d3dc861488b2b4e89cc1696d6e43bd9cb8b
- 73c752bb19e98f0a48c8793cb3d274974ddaa1be
- 5b7f4ebda028b7fb4b6ad171a159db54ee0258a0
- 887a3819ed33a2aa583de1bc2bdf346b107c36cb
- 6b0bbf3d5f3715a3e04389419a51d2031ca9bacb
- 6d72e62f15e43def91a7c494b7f303a08fb270da
- e465ed550d3660c0cd3cd41350747cf1477c6584
- f70c82367a1ed3ee464c1800f0e2342b3cb86c3f
- 1662f4783b9367abcb191386881f6105e3db3227
- be0acf544fa84f001f3d0c69a2039ceb1668e3a5
- 5d03b548f191bb73d6e931314a7c375b9c2c077b
- 1dff4c4f54dcc8a94719a6f2ed6601953ca3af81
- cdc665a9597d05c4280d93ae1fd9591c3e17bc27
- 15c9e7a1a7ffcc946c4fc97f38ab2bb8742288bc
- 4e6170103975a2bb839cb843c0a089adcd0fee25
- 2fc50af8155d0ba76c12f429e9ecab4dbd8e7000
- 82546b011fc8a9979d9027e2e141edc7aa8f3341
- daf9a5a68f7dbd856cc9b8ab08e5a1d53784e9d6
- d460516891713a18a5cdda8d3dd177f8ad6b9d09
- 567d6ce944b2a628ccd6c1e01fb2f1fd6414f133
- 086533b109678ed999a9f16f5a95dde883bd9554

## Dropped commmits

- 68f62f354adcb7ff450ad840f9e2fc25eb7c3182
- 51d0e74e7514f34bbf8632c0f0e3c87d0696ce75
- 0deaf2f0975604822ea8166ff7cadcf163557093
- 736fb23c30687500be8ef2130e3ca9d1df4c7974
- 7920515da6d660f07189e06afb79bd002c12c55f
- 4f1b9277555e7010d7f32665a10ad72344ce8f92
- 7108af75d20db6b47c90192626ab646008636aff

## Dropped commits WITH TODOs

- [x] f6f519cb099b3187131ee68a067b986f9228c306 (opened https://github.com/mozilla-services/cloudops-deployment/pull/3153) @jasonthomas @jezdez
- [ ] 1f29990bf337d8981efffcbff9e4bc1c8c9a0145 @washort

## Collapsed commits (of the applied above)

1. Schema Drawer

- cc9e0a415: Add column type info to query runners (re #152, #23)
- e3f48b4d3: Schema Viewer Drawer (#3291)
- 70079d754: fix for #2426 test
- 5a736440f: more stable test_interactive_new
- d0ac040fc: Closes #927, #928: Schema refresh improvements.
- b2ac12b89: Schema refresh review fixes.
- cdae8f9eb: Another follow-up to #930
- 052b5d03b: Addressing sentry issues.
- ca04a09ba: Closes #934, #935: Remove type from schema browser and don't show empty example column in -chema drawer (#936)
- 7bc7090f0: Closes #939: Persisted, existing table metadata should be updated.
- 885d73f98: Sample processing should be rate-limited.
- 4df5273bb: Add cli command for refreshing data samples.
- f5baa9b9e: Schema refreshes should not overwrite column 'example' field.
- 23f98faad: refresh_samples() should filter tables_to_sample on the datasource's id being sampled
- 077ea6a01: Correctly wrap long text in schema drawer.

2. Circle CI setup

- 9372e73a9: Update Circle CI for our workflow
- e9d733972: Fix yaml and add tag filters for other tests (#923)
- a76333615: Don't use extra hyphens in our custom version.
- 1b088ec4a: Appease SemVer by using - instead of +.

### CODE REVIEW

**Comment by emtwo** [comment]
There are 6 commits up at https://github.com/mozilla/redash/tree/emtwo/m21 : 

* The first 3 are a rebase of  567d6ce and 086533b
* The 4th is a bug fix I found in the pg query. I think it may have been a rebase error?
* The 5th one is to bring toggling back.
* The 6th one took a bit of exploration. Essentially, it looks like when I checked out the `release` branch and tested it locally, version and doc url were available. However they don't seem available in r-c which makes me suspect maybe there is an issue with deploying the extensions? 

However, the only *minor* issue is that when a *new* data source is created, it doesn't automatically populate the version toggle or doc url, they remain empty. So by default these features would not be on. I am just proposing a way in that commit to make them default on.

**Comment by jezdez** [comment]
> There are 6 commits up at [/m21@`emtwo`](https://github.com/mozilla/redash/tree/emtwo/m21) [](/mozilla/redash/tree/HEAD@{2019-05-15T21:26:35Z}/m21) :
> 
>     * The first 3 are a rebase of  [567d6ce](https://github.com/mozilla/redash/commit/567d6ce944b2a628ccd6c1e01fb2f1fd6414f133) and [086533b](https://github.com/mozilla/redash/commit/086533b109678ed999a9f16f5a95dde883bd9554)
> 
>     * The 4th is a bug fix I found in the pg query. I think it may have been a rebase error?
> 
>     * The 5th one is to bring toggling back.

I've merged those commits into the individual feature commits.

>     * The 6th one took a bit of exploration. Essentially, it looks like when I checked out the `release` branch and tested it locally, version and doc url were available. However they don't seem available in r-c which makes me suspect maybe there is an issue with deploying the extensions?

Hm, that'd be odd, I'll double check this..

> However, the only _minor_ issue is that when a _new_ data source is created, it doesn't automatically populate the version toggle or doc url, they remain empty. So by default these features would not be on. I am just proposing a way in that commit to make them default on.

Ok, let's go with the patch and see if this makes sense. Can you follow-up with this upstream after the deploy?

**Comment by emtwo** [comment]
> > * The 6th one took a bit of exploration. Essentially, it looks like when I checked out the `release` branch and tested it locally, version and doc url were available. However they don't seem available in r-c which makes me suspect maybe there is an issue with deploying the extensions?
> >
> 
> Hm, that'd be odd, I'll double check this..

Yes thank you I wanted to also ask if you could do that.

> 
> > However, the only _minor_ issue is that when a _new_ data source is created, it doesn't automatically populate the version toggle or doc url, they remain empty. So by default these features would not be on. I am just proposing a way in that commit to make them default on.
> 
> Ok, let's go with the patch and see if this makes sense. Can you follow-up with this upstream after the deploy?

Well this patch is a proposal so it would need more changes to work for all data source. I've only done it for postgres as an example. It would also need a change in the `redash-stmo` repo for doc_url to work.

I can file an issue upstream though I think this might be intended behaviour. Given the fact that this is a small issue with intended behaviour and requires changes to `redash-stmo`, I'm wondering if we can postpone addressing this to the next release? I think more importantly would be to address the above issue to see why it works on the release branch but not r-c

**Comment by jezdez** [comment]
> > > * The 6th one took a bit of exploration. Essentially, it looks like when I checked out the `release` branch and tested it locally, version and doc url were available. However they don't seem available in r-c which makes me suspect maybe there is an issue with deploying the extensions?
> > 
> > 
> > Hm, that'd be odd, I'll double check this..
> 
> Yes thank you I wanted to also ask if you could do that.
> 
> > > However, the only _minor_ issue is that when a _new_ data source is created, it doesn't automatically populate the version toggle or doc url, they remain empty. So by default these features would not be on. I am just proposing a way in that commit to make them default on.
> > 
> > 
> > Ok, let's go with the patch and see if this makes sense. Can you follow-up with this upstream after the deploy?
> 
> Well this patch is a proposal so it would need more changes to work for all data source. I've only done it for postgres as an example. It would also need a change in the `redash-stmo` repo for doc_url to work.
> 
> I can file an issue upstream though I think this might be intended behaviour. Given the fact that this is a small issue with intended behaviour and requires changes to `redash-stmo`, I'm wondering if we can postpone addressing this to the next release? I think more importantly would be to address the above issue to see why it works on the release branch but not r-c

Makes sense to me, I'll remove 

> > > * The 6th one took a bit of exploration. Essentially, it looks like when I checked out the `release` branch and tested it locally, version and doc url were available. However they don't seem available in r-c which makes me suspect maybe there is an issue with deploying the extensions?
> > 
> > 
> > Hm, that'd be odd, I'll double check this..
> 
> Yes thank you I wanted to also ask if you could do that.

Sure no problem.

> 
> > > However, the only _minor_ issue is that when a _new_ data source is created, it doesn't automatically populate the version toggle or doc url, they remain empty. So by default these features would not be on. I am just proposing a way in that commit to make them default on.
> > 
> > 
> > Ok, let's go with the patch and see if this makes sense. Can you follow-up with this upstream after the deploy?
> 
> Well this patch is a proposal so it would need more changes to work for all data source. I've only done it for postgres as an example. It would also need a change in the `redash-stmo` repo for doc_url to work.
> 
> I can file an issue upstream though I think this might be intended behaviour. Given the fact that this is a small issue with intended behaviour and requires changes to `redash-stmo`, I'm wondering if we can postpone addressing this to the next release? I think more importantly would be to address the above issue to see why it works on the release branch but not r-c

Okay, that works for me, so I'm removing e999042b1c5a1075bb8143dcebc3e84f292316f6 again?

**Comment by emtwo** [comment]
> Okay, that works for me, so I'm removing [e999042](https://github.com/mozilla/redash/commit/e999042b1c5a1075bb8143dcebc3e84f292316f6) again?

Yes please. Sorry for the confusion

**Comment by jezdez** [comment]
> > Okay, that works for me, so I'm removing [e999042](https://github.com/mozilla/redash/commit/e999042b1c5a1075bb8143dcebc3e84f292316f6) again?
> 
> Yes please. Sorry for the confusion

All good, just wanted to be clear. 👍

**Comment by jezdez** [comment]
This has been pushed to release.

**Comment by jezdez** [comment]
Closing since this has been merged and released.

**Pull request closed without merging**
