### PR TITLE
Only load fields that are needed from Google API for Big Query schema.

### PR DESCRIPTION
**Pull request by jezdez**
Refs #785.

I used the Google API Explorer to build the values for the fields parameters: e.g. https://developers.google.com/apis-explorer/#p/bigquery/v2/bigquery.tables.get

More info for the fields parameter: https://developers.google.com/api-client-library/python/guide/performance#partial-response-fields-parameter

### CODE REVIEW

**Comment by jezdez** [comment]
It'd be neat to try this out eventually, not sure how I can do this locally to be honest :(

**Comment by jasonthomas** [comment]
>  Is there any chance we could do that, @jasonthomas?

@emtwo I've sent you an email with the json key. The project id information is also listed in the json key file.

One thing to mention is that the redash documentation recommends either using the Big Query Admin role or creating a custom role for the service account with the permissions. I've created a custom role with the following permissions:

```
    "bigquery.datasets.get",
    "bigquery.jobs.create",
    "bigquery.jobs.get",
    "bigquery.jobs.list",
    "bigquery.jobs.listAll",
    "bigquery.jobs.update",
    "bigquery.tables.get",
    "bigquery.tables.list",
```
The documentation also includes 'bigquery.datasets.list' and 'bigquery.tables.getData' which is not included in the above permissions. 'bigquery.datasets.list' does not exist and ''bigquery.tables.getData'  would give access to all table data. Instead the service account user has access to specific datasets/tables. 

[1] https://redash.io/help/data-sources/setup/bigquery
[2] https://cloud.google.com/bigquery/docs/access-control

**Comment by jasonthomas** [comment]
As per today's STMO meeting we decided to test the BigQuery data source with a a gcp service account that contained role 'BigQuery Admin' to rule out this is a permission issue.

I created a new service account, created a new Big Query data source on stage stmo and was unable to view the schema. The error was the same as above ```{"error": {"message": "Error retrieving schema.", "code": 2}}```. I also ran a query against the datasource and that was successful and returned data.

**Comment by jezdez** [comment]
Hey @emtwo, @jasonthomas Do you think this would be a good idea to open a PR upstream?

**Comment by emtwo** [comment]
> Do you think this would be a good idea to open a PR upstream?

Yes definitely.

**Comment by jezdez** [comment]
Closing in favor of https://github.com/getredash/redash/pull/3673.

**Pull request closed without merging**
