### PR TITLE
Bug 1251663 - Add presto query cancellation

### PR DESCRIPTION
**Pull request by fbertsch**
@robotblake, r?

### CODE REVIEW

**Comment by robotblake** [comment]
Should we change `requirements_all_ds.txt` to point to our PyHive fork or is that included in the latest PyHive release?

**Comment by fbertsch** [comment]
The changes will be available in the next PyHive, it does indeed need to point to ours for now.

**Comment by fbertsch** [comment]
@robotblake I've made the change. I wanted to ensure everything works, but I can't get the tests to run in circleci, because it doesn't boot redis. It does download our PyHive package, which you can test in a virtualenv.

Should we push this for now, and make a bug about getting circleci working for our redash repo?

**Comment by arikfr** [comment]
If you use our CircleCI yml file, you probably need to specify Redis as a
service. We didn't have to do it as we use their legacy stack but new
projects need to do it.

**Comment by fbertsch** [comment]
@arikfr, thanks for the tip. I'm testing it out now.

**Comment by arikfr** [comment]
You will also need to specify Postgres.

**Comment by fbertsch** [comment]
Got it working, thanks @arikfr!

@robotblake, RFAL

**Pull request merged**
