### PR TITLE
320 fix query pagination alignment

### LINKED ISSUE #320: The navigation displayed in the query source page is not centered
### Steps to Reproduce:
1. Execute this query: https://pipeline-sql.stage.mozaws.net/queries/271/source
2. Scroll down and observe the navigation between result pages

### Expected results:
The navigation is centred

### Actual results:
The navigation aligned to left.

### Notes/Issues:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Verified in FF58(Win7).  Issue can be reproduced in STMO-stage
navigationalignment

### PR DESCRIPTION
**Pull request by alison985**
fixes #320 
also fixes annoying space issue

### CODE REVIEW

**Comment by alison985** [comment]
upstream PR https://github.com/getredash/redash/pull/2570

**Comment by jezdez** [comment]
@alison985 Let's wait how the upstream is PR ends up before merging this..

**Comment by alison985** [comment]
merged upstream

**Comment by jezdez** [comment]
Yay!

**Pull request closed without merging**
