### PR TITLE
Closes #427: Migrate schedule_until into new json schedule field.

### LINKED ISSUE #427: Port schedule_until feature to upstream
Add `schedule_until` field to queries, to allow expiry (#15, PR: #60)

This is tracked on https://github.com/mozilla/redash/projects/3

### PR DESCRIPTION
**Pull request by emtwo**
This migration should be applied after this PR lands upstream: https://github.com/getredash/redash/pull/2426 and is merged into our fork.

### CODE REVIEW

**Comment by jezdez** [comment]
@emtwo Would you mind rebasing this, since that's the next step to close #427 after https://github.com/getredash/redash/pull/2426 got merged?

**Comment by emtwo** [comment]
I've rebased this PR with 2 notes to make:

* This is now based on the last upstream migration which returned the ability for the `schedule` field to be null: https://github.com/getredash/redash/commit/e8120c5f79cca01b5a011e8197c4cd604bf718d9#diff-ae8945bd01a33cb1ff4e201d68685558
* I've removed references to `schedule_until` from `models.py` and `serializers.py` in this PR as well, but these may not be necessary depending on if it takes place when we pull in the latest upstream code.

**Comment by jezdez** [comment]
@emtwo I'm sorry but could you please do another rebase for this?

**Comment by jezdez** [comment]
This was ported into the master branch in https://github.com/mozilla/redash/commit/0deaf2f0975604822ea8166ff7cadcf163557093 (via https://github.com/mozilla/redash/pull/922).

**Pull request closed without merging**
