### PR TITLE
152 add db column type schema browser

### PR DESCRIPTION
**Pull request by alison985**
#152 #23

### CODE REVIEW

**Comment by washort** [comment]
r+

**Comment by vcarciu** [comment]
Please add some STRs to this issue

**Comment by alison985** [comment]
@vcarciu 
1. Login to re:dash and go to the query page.
2. Select a the metadata data source from the drop-down menu.
3. The schema browser should come up (or is already) on the left of the screen.
4. Click on a table to open the list of fields.

passing:
You see the field type in () at the end of the line.

failing:
You only see the field name without the type.

**Comment by vcarciu** [comment]
I am still seeing only the field name without the type on Stage : https://www.screencast.com/t/TIVm7Q24I5C

**Comment by alison985** [comment]
Interesting @vcarciu - I see them on staging: https://www.dropbox.com/s/ul308cw41kpbljr/Screenshot%202017-08-09%2011.51.51.png?dl=0 

What URL were you at for the screencast?

**Comment by vcarciu** [comment]
Hello @alison985  ,

It looks that it is working now for me too for "Redash Metadata" data source, but not for other source . Please see a screencast for "Athena" data source(you can see the url in screencast) :  https://www.screencast.com/t/btrad3uDX7Q

**Comment by alison985** [comment]
@vcarciu I don't know why this isn't working for Athena, but it is working for postgres and not causing any other issues so I'm not going to delay M8 release. I will open a bug for looking into the Athena issue.

**Comment by vcarciu** [comment]
@alison985 : please note that this is working only for "Redash metadata" , so if you open a separate issue, please open for all the other data sources.

**Pull request merged**
